// L1 블록체인 섹터 매핑
export const L1_BLOCKCHAIN_SECTORS: { [key: string]: string } = {
  // 메인 L1 블록체인
  BTC: "가치저장/P2P결제",
  ETH: "L1/스마트컨트랙트",
  BNB: "L1/생태계유틸리티",
  SOL: "L1/고성능",
  ADA: "L1/학술기반PoS",
  AVAX: "L1/서브넷",
  DOT: "인터체인/파라체인허브",
  TRX: "L1/콘텐츠&결제",
  TON: "L1/소셜네트워크",
  NEAR: "L1/샤딩",
  ICP: "L1/분산형클라우드",
  ATOM: "인터체인/IBC허브",
  APT: "L1/Move언어",
  SUI: "L1/Move언어(자산중심)",
  HBAR: "L1/해시그래프(기업용)",
  ALGO: "L1/순수지분증명(PPoS)",
  CFX: "L1/Tree-Graph(중국)",
  KAIA: "L1/통합(클레이튼+핀시아)",
  SEI: "L1/트레이딩최적화",
  KLAY: "L1/카카오(KAIA에통합)",
  
  // 기타 L1 블록체인
  WAVES: "L1/Web3앱플랫폼",
  NEO: "L1/디지털자산(중국)",
  EOS: "L1/DPoS",
  QTUM: "L1/하이브리드(UTXO+EVM)",
  ONT: "L1/탈중앙화신원(DID)",
  ZIL: "L1/샤딩",
  FLOW: "L1/NFT&게임",
  ROSE: "L1/프라이버시&데이터",
  ONE: "L1/샤딩&크로스체인",
  EGLD: "L1/샤딩(구Elrond)",
  FTM: "L1/DAG기반",
  CELO: "L1/모바일금융",
  MINA: "L1/경량블록체인(zk-SNARK)",
  BEAM: "L1/GameFi네트워크",
  CORE: "L1/SatoshiPlus합의",
  BSV: "L1/비트코인포크",
  ETC: "L1/이더리움오리지널(PoW)",
  INJ: "L1/DeFi최적화",
  BB: "L1/비트코인리스테이킹",
  IOST: "L1/PoB합의",
  ORBS: "L1/하이브리드(실행레이어)",
  AERGO: "L1/하이브리드(기업용)",
  CRO: "L1/EVM호환(Crypto.com)",
  CHR: "L1/관계형블록체인",
  CSPR: "L1/PoS(기업용)",
  BOA: "L1/DAO기반",
  OAS: "L1/게임최적화",
  XPLA: "L1/게임&콘텐츠(Com2uS)",
  REI: "L1/경량EVM",
  ARDR: "L1/부모-자식체인(BaaS)",
  CKB: "L1/UTXO(비트코인L2솔루션)",
  XTZ: "L1/자체수정거버넌스",
  FLR: "L1/이더리움시계열데이터",
  KAVA: "L1/DeFi블록체인(코스모스)",
  LSK: "L1/자바스크립트SDK",
  STRAX: "L1/엔터프라이즈블록체인",
  QKC: "L1/샤딩블록체인",
  ARK: "L1/브리지체인",
  TT: "L1/뉴저리합의",
  ELF: "L1/클라우드컴퓨팅",
  SONIC: "L1/게이밍SVM",
  BERA: "레이어1", // 베라체인 - EVM 호환 고성능 블록체인
  G: "레이어1", // 그래비티 - 웹3 대중화, 옴니체인 플랫폼
  
  // L1 유틸리티 토큰들
  GAS: "L1/유틸리티(NEO)",
  ONG: "L1/유틸리티(Ontology)",
  VTHO: "L1/유틸리티(VeChain)",
};
