// 카테고리별 분류
export const CRYPTO_CATEGORIES = {
  ZK_INFRA: ["LA", "PROVE"],
  MAJOR: ["BTC", "ETH", "XRP", "LTC", "BCH", "BNB", "ETC"], // 시총/역사성 고려해 BNB, ETC 포함 [21][22]
  DEFI: [
    "UNI",
    "AAVE",
    "COMP",
    "SUSHI",
    "CRV",
    "BAL",
    "YFI",
    "SNX",
    "MKR",
    "DYDX",
    "GMX",
    "1INCH",
    "CAKE",
    "JOE",
    "PENDLE",
    "JUP",
    "RAY",
    "ORCA",
    "RDNT",
    "MORPHO",
    "AERO",
    "VELO",
    "VELODROME",
    "LISTA",
  ], // AMM/애그리게이터/렌딩/수익토큰화 추가 [22][21]
  LAYER1: [
    "SOL",
    "ADA",
    "DOT",
    "AVAX",
    "ATOM",
    "NEAR",
    "ALGO",
    "HBAR",
    "TRX",
    "TON",
    "SUI",
    "APT",
    "BNB",
    "ICP",
    "EGLD",
    "FTM",
    "CELO",
    "CFX",
    "KAIA",
    "KLAY",
    "NEO",
    "EOS",
    "QTUM",
    "ONT",
    "ZIL",
    "ONE",
    "CORE",
    "CRO",
    "ORBS",
    "AERGO",
  ], // L1 명시 코인 보강 [22][21]
  LAYER2: [
    "ARB",
    "OP",
    "MATIC",
    "POL",
    "STRK",
    "METIS",
    "BOBA",
    "LRC",
    "BLAST",
    "SCROLL",
    "SCR",
    "LINEA",
    "ZK",
    "TAIKO",
    "MANTA",
    "TOKAMAK",
  ], // L2/ZK 롤업 계열 추가, POL=prev. MATIC 맵 유지 [8][4]
  GAMING: [
    "AXS",
    "SLP",
    "SAND",
    "MANA",
    "ENJ",
    "GALA",
    "IMX",
    "ALICE",
    "YGG",
    "MAGIC",
    "RON",
    "ILV",
    "BIGTIME",
    "AGLD",
    "XAI",
  ], // GameFi/메타버스/퍼블리싱 [22][21]
  MEME: [
    "DOGE",
    "SHIB",
    "PEPE",
    "FLOKI",
    "BONK",
    "WIF",
    "BRETT",
    "NEIRO",
    "PENGU",
    "POPCAT",
    "MEW",
    "PONKE",
    "SUNDOG",
    "ANIME",
    "RETARDIO",
    "CHILLGUY",
    "MOODENG",
    "PNUT",
    "GOAT",
    "SPX",
    "TURBO",
    "FARTCOIN",
  ], // 밈/커뮤니티 토큰 확장 [23][22]
  KOREAN: [
    "ICX",
    "KLAY",
    "KAIA",
    "BORA",
    "TEMCO",
    "META",
    "SSX",
    "MVL",
    "MED",
    "HUNT",
    "WEMIX",
    "MBL",
    "BFC",
    "TOKAMAK",
  ], // 한국 프로젝트 보강 [22][21]
  AI: [
    "WLD",
    "FET",
    "AGIX",
    "RENDER",
    "TAO",
    "OCEAN",
    "IO",
    "ARKM",
    "VIRTUAL",
    "AI16Z",
    "AIOZ",
    "LA",
  ], // AI/에이전트·데이터: VIRTUAL, AI16Z 포함 [6][7]
  INFRASTRUCTURE: [
    "LINK",
    "GRT",
    "AR",
    "FIL",
    "STORJ",
    "LPT",
    "THETA",
    "ANKR",
    "POKT",
    "RLC",
    "GLM",
    "AKT",
    "FLUX",
    "LA",
  ], // 인덱싱/미디어/노드/컴퓨팅 [24][22]
  STAKING: [
    "LDO",
    "RPL",
    "EIGEN",
    "ETHFI",
    "PUFFER",
    "JTO",
    "FRXETH",
    "STETH",
    "RETH",
    "SWISE",
    "BABY",
  ], // LST/LRT 계열 확대 [22][21]
  ORACLE: ["LINK", "BAND", "API3", "PYTH", "UMA"], // 유지 [22][21]
  STABLECOIN: [
    "USDT",
    "USDC",
    "DAI",
    "FRAX",
    "USDS",
    "BUSD",
    "TUSD",
    "USD1",
    "FXS",
  ], // 스테이블/연동 [22][21]
  PRIVACY: ["ZEC", "XMR", "DASH", "T", "ARPA", "OXT", "SCRT"], // 프라이버시 보강 [22][21]
  PAYMENT: ["XRP", "XLM", "ACH", "AMP", "REQ", "PUNDIX", "SXP", "MTL", "XCN"], // 결제/인보이스/담보 [22][21]
  STORAGE: ["FIL", "AR", "STORJ", "SC", "BTT"], // 유지 [22][21]
  ALTCOIN: [], // 기본 카테고리 (매칭되지 않은 코인들) [22][21]
};

// 카테고리별 우선순위 (높을수록 우선)
export const CATEGORY_PRIORITY = {
  MAJOR: 10,
  DEFI: 9,
  LAYER1: 8,
  LAYER2: 7,
  AI: 6,
  ZK_INFRA: 6, // AI, Layer2와 유사한 중요도를 가짐
  GAMING: 5,
  KOREAN: 5,
  MEME: 4,
  INFRASTRUCTURE: 4,
  STAKING: 3,
  ORACLE: 3,
  STABLECOIN: 3,
  PRIVACY: 2,
  PAYMENT: 2,
  STORAGE: 2,
  ALTCOIN: 1,
};
