// 빗썸 거래 가능 암호화폐 한국어 매핑
export const CRYPTO_KOREAN_NAMES: { [key: string]: string } = {
  BTC: "비트코인",
  ETH: "이더리움",
  XRP: "리플",
  LTC: "라이트코인",
  ETC: "이더리움 클래식",
  ADA: "에이다",
  BCH: "비트코인 캐시",
  SOL: "솔라나",
  AVAX: "아발란체",
  DOT: "폴카닷",
  MATIC: "폴리곤",
  DOGE: "도지코인",
  TRX: "트론",
  SHIB: "시바이누",
  LINK: "체인링크",
  UNI: "유니스왑",
  ATOM: "코스모스",
  VET: "비체인",
  ICP: "인터넷 컴퓨터",
  FIL: "파일코인",
  SAND: "더 샌드박스",
  MANA: "디센트럴랜드",
  CRO: "크로노스",
  APT: "앱토스",
  NEAR: "니어 프로토콜",
  ALGO: "알고랜드",
  HBAR: "헤데라",
  QNT: "퀀트",
  VRA: "베라시티",
  CHZ: "칠리즈",
  BAT: "베이직 어텐션 토큰",
  THETA: "세타",
  CVC: "시빅",
  WAVES: "웨이브",
  ENJ: "엔진코인",
  MTL: "메탈",
  IOST: "아이오에스티",
  CTXC: "코텍스",
  HOT: "홀로체인",
  ICX: "아이콘",
  OMG: "오미세고",
  ZIL: "질리카",
  QTUM: "퀀텀",
  LSK: "리스크",
  STEEM: "스팀",
  STRK: "스트라이크",
  ARDR: "아더",
  STORJ: "스토리지",
  GRT: "더 그래프",
  TFUEL: "세타 퓨얼",
  KLAY: "클레이튼",
  XLM: "스텔라루멘",
  POWR: "파워렛저",
  PCI: "페이프로토콜",
  XTZ: "테조스",
  SRM: "세럼",
  ORBS: "오브스",
  BORA: "보라",
  JST: "저스트",
  CTC: "크레딧코인",
  FCT2: "피르마체인",
  SSX: "썸씽",
  META: "메타디움",
  SXP: "스와이프",
  HIBS: "하이버나투스",
  TEMCO: "템코",
  BIOT: "바이오패스포트",
  HIVE: "하이브",
  XEC: "이캐시",
  AAVE: "아베",
  COMP: "컴파운드",
  YFI: "연파이낸스",
  SNX: "신세틱스",
  UMA: "우마",
  SUSHI: "스시스왑",
  CRV: "커브",
  BAL: "밸런서",
  RSR: "리저브라이츠",
  PUNDIX: "펀디엑스",
  NPT: "네오핀",
  AXS: "액시 인피니티",
  SLP: "스무스 러브 포션",
  CYBER: "사이버커넥트",
  ARB: "아비트럼",
  PEPE: "페페",
  FLOKI: "플로키",
  BONK: "봉크",
  PYTH: "피스 네트워크",
  JUP: "주피터",

  // 추가 코인들
  A: "아라곤",
  GLM: "골렘",
  ZRX: "0x",
  SNT: "스테이터스",
  AMO: "아모코인",
  BSV: "비트코인 SV",
  ANKR: "앵커",
  MIX: "믹스마블",
  CHR: "크로미아",
  MBL: "무비블록",
  BOA: "보사고라",
  MEV: "미버스",
  COS: "컨텐토스",
  EL: "엘리시아",
  XPR: "프로톤",
  EGG: "구스 파이낸스",
  ARPA: "알파 체인",
  APM: "APM 코인",
  CKB: "너보스 네트워크",
  AERGO: "아르고",
  EVZ: "에바네스코 네트워크",
  NMR: "뉴메레어",
  RLC: "아이젝 RLC",
  UOS: "울트라",
  AWE: "AWE",
  BEL: "벨라 프로토콜",
  OBSR: "옵저버",
  POLA: "폴라 싱크",
  ADP: "어댑터 토큰",
  DVI: "디비전 네트워크",
  GHX: "게이머해시",
  CBK: "코박 토큰",
  MVC: "마일버스",
  BLY: "블로서리",
  GRACY: "그레이시",
  OXT: "오키드",
  MAPO: "MAP 프로토콜",
  AQT: "알파 쿼크 토큰",
  WIKEN: "프로젝트 시드",
  CTSI: "카르테시",
  LPT: "라이브피어",
  CELR: "셀러 네트워크",
  SLF: "셀프키",
  BFC: "바이프로스트",
  ALICE: "마이네이버앨리스",
  OGN: "오리진 프로토콜",
  COTI: "코티",
  CAKE: "팬케이크스왑",
  BNT: "뱅코르",
  XVS: "비너스",
  SWAP: "트러스트스왑",
  LRC: "루프링",
  KNC: "카이버 네트워크",
  ELF: "엘프",

  // 새로 추가된 코인들
  SOFI: "로켓X 익스체인지",
  KAITO: "카이토 AI",
  IQ: "아이큐",
  FLUX: "플럭스",
  JASMY: "재스미코인",
  REQ: "리퀘스트",
  WOO: "우 네트워크",
  ARKM: "아캄",
  RSS3: "RSS3",
  FXS: "프랙스 셰어",
  PONKE: "폰케",
  TURBO: "터보",
  AIOZ: "AIOZ 네트워크",

  // 2024년 메인 신규 코인들
  HYPE: "하이프",
  VIRTUAL: "버추얼 프로토콜",
  MOVE: "무브먼트",
  ME: "매직에덴",
  PENGU: "펭구",
  USUAL: "유쥬얼",
  VELODROME: "벨로드롬",
  EIGEN: "아이겐레이어",
  ONDO: "온도 파이낸스",
  ETHFI: "이더파이",
  PUFFER: "퍼퍼",
  ENA: "에테나",
  MORPHO: "모르포",
  AERO: "에어로드롬",
  VELO: "벨로코어",
  ZEREBRO: "제레브로",
  AI16Z: "AI16Z",
  VIRTUALS: "버추얼스",
  AIXBT: "AIXBT",
  ACT: "ACT",
  RETARDIO: "리타디오",
  CHILLGUY: "칠가이",
  MOODENG: "무덩",
  PNUT: "피넛",
  GOAT: "고트",
  NEIRO: "네이로",
  SPX: "SPX6900",
  FARTCOIN: "파트코인",

  // 추가 누락된 주요 코인들
  WAXP: "왁스",
  DAO: "DAO메이커",
  SIX: "식스",
  POL: "폴리곤",
  ACH: "알케미페이",
  ONT: "온톨로지",
  KAIA: "카이아",
  ONG: "온톨로지 가스",
  MLK: "밀크",
  KSM: "쿠사마",
  CTK: "컨텍",
  BNB: "바이낸스 코인",
  NFT: "에이피이앤에프티",
  SUN: "선",
  EGLD: "멀티버스X",
  MASK: "마스크 네트워크",
  C98: "코인98",
  MED: "메디블록",
  "1INCH": "1인치",
  BOBA: "보바 네트워크",
  USDS: "유에스디에스",

  // 추가 신규 코인들
  GRASS: "그래스",
  ORCA: "오르카",
  PUMP: "펌프",
  EPT: "벨런스",
  HAEDAL: "해달",
  PARTI: "파티",
  SXT: "SXT",
  PROMPT: "프롬프트",
  SIGN: "사인",
  SAHARA: "사하라",
  H: "H",
  HOME: "홈",
  OM: "OM",
  LA: "라그랑쥬",
  SOPH: "소프",
  HYPER: "하이퍼",
  PROVE: "프루브",
  FORT: "포트",
  HUMA: "휴마",
  SPK: "스파크",
  USD1: "USD1",
  SYRUP: "시럽",
  NEWT: "뉴트",
  RESOLV: "리졸브",
  TREE: "트리",
  EUL: "율러",
  SD: "SD",
  TOWNS: "타운즈",
  CAMP: "캠프 네트워크",
  WLFI: "월드 리버티 파이낸셜",
  H: "휴머니티 프로토콜",
  PUMPBTC: "펌프비티씨",
  PUMP: "펌프닷펀",

  // 대량 추가 코인들
  OPEN: "오픈렛저",
  SOON: "쑨",
  ATH: "에이셔",
  OMNI: "옴니 네트워크",
  UXLINK: "유엑스링크",
  TAVA: "알타바",
  DRIFT: "드리프트",
  WAXL: "엑셀라",
  W: "웜홀",
  MEW: "캣인어독스월드",
  NXPC: "넥스페이스",
  MAV: "매버릭 프로토콜",
  BRETT: "브렛",
  BIO: "바이오 프로토콜",
  PLUME: "플룸",
  C: "체인베이스 토큰",
  ROA: "로아코어",
  RED: "레드스톤",
  FIDA: "솔라나 네임 서비스",
  AVL: "아발론",
  SHELL: "마이쉘",
  ES: "이클립스",
  SKY: "스카이 프로토콜",
  BIGTIME: "빅타임",
  KERNEL: "커널 다오",
  ALT: "알트레이어",
  MERL: "멀린 체인",
  TAIKO: "타이코",
  BERA: "베라체인",
  STAT: "스탯",
  ERA: "칼데라",
  XTER: "엑스테리오",
  LAYER: "솔레이어",
  ANIME: "애니메코인",
  XCN: "오닉스코인",
  LBL: "레이블 에이아이",
  WCT: "월렛커넥트",
  VANA: "바나",
  COOKIE: "쿠키 다오",
  LDO: "리도다오",
  RAY: "레이디움",
  ELX: "엘릭서",
  ZTX: "지티엑스",
  SWELL: "스웰 네트워크",
  AHT: "아하토큰",
  F: "신퓨처스",
  BMT: "버블맵스",
  REI: "레이",
  AKT: "아카시 네트워크",
  A8: "에인션트8",
  AVAIL: "어베일",
  XAI: "자이",
  WNCG: "랩트 나인 크로니클 골드",
  OBT: "오비터 파이낸스",
  HOOK: "훅트 프로토콜",
  NCT: "폴리스웜",
  MAGIC: "매직",
  BLUE: "블루핀",
  BABY: "바빌론",
  JTO: "지토",
  SPURS: "토트넘 홋스퍼",
  ZRC: "저킷",
  BB: "바운스빗",
  RVN: "레이븐코인",
  FANC: "팬시",
  RPL: "로켓풀",
  MOCA: "모카네트워크",
  ZRO: "레이어제로",
  EDU: "오픈 캠퍼스",
  SONIC: "소닉 에스브이엠",
  ACS: "액세스프로토콜",
  STRAX: "스트라티스",
  GTC: "깃코인",
  HFT: "해시플로우",
  DEEP: "딥북",
  DBR: "디브릿지",
  LM: "레저메타",
  BLUR: "블러",
  GMT: "스테픈",
  MBX: "마브렉스",
  GAS: "가스",
  API3: "에이피아이쓰리",
  SCR: "스크롤",
  WAL: "월러스",
  NIL: "닐리온",
  ILV: "일루비움",
  B3: "비쓰리",
  CARV: "카브",
  SOLV: "솔브 프로토콜",
  LWA: "루미웨이브",
  S: "소닉",
  POLYX: "폴리매쉬",
  INIT: "이니시아",
  CORE: "코어",
  GRND: "슈퍼워크",
  MAY: "메이플라워",
  LISTA: "리스타 다오",
  BEAM: "빔",
  POKT: "포켓네트워크",
  ORDER: "오덜리 네트워크",
  ZK: "지케이싱크",
  PEAQ: "피크",
  AZIT: "아지트",
  WIF: "도그위프햇",
  OAS: "오아시스",
  CRTS: "크라토스",
  STG: "스타게이트 파이낸스",
  IOTX: "아이오텍스",
  MANTA: "만타 네트워크",
  ACE: "퓨저니스트",
  REZ: "렌조",
  ACX: "어크로스 프로토콜",
  ID: "스페이스 아이디",
  RAD: "래드웍스",
  D: "달 오픈 네트워크",
  AL: "아치루트",
  T: "쓰레스홀드",
  ASTR: "아스타",
  TT: "썬더코어",
  VTHO: "비토르 토큰",
  YGG: "일드길드게임즈",
  DYDX: "디와이디엑스",
  SC: "시아코인",
  METIS: "메티스다오",
  AR: "알위브",
  RON: "로닌",
  AGLD: "어드벤처골드",
  HP: "히포 프로토콜",
  FITFI: "스텝앱",
  PYR: "불칸 포지드",
  QKC: "쿼크체인",
  AUDIO: "오디우스",
  MVL: "엠블",
  SAFE: "세이프",
  MOC: "모스코인",
  KAVA: "카바",
  GAME2: "게임빌드",
  GMX: "지엠엑스",
  AMP: "앰프",
  G: "그래비티",
  BOUNTY: "체인바운티",
  BICO: "바이코노미",
  DKA: "디카르고",
  HIGH: "하이스트리트",
  HUNT: "헌트",
  OSMO: "오스모시스",
  GNO: "노시스",
  GRS: "그로스톨코인",
  SFP: "세이프팔",

  // 한국 프로젝트 추가 매핑
  WEMIX: "위믹스",
  TOKAMAK: "토카막 네트워크",
};

// 대체 한글 이름 매핑 (fallback)
export const FALLBACK_KOREAN_NAMES: { [key: string]: string } = {
  WAXP: "왁스",
  DAO: "DAO메이커",
  POL: "폴리곤",
  ACH: "알케미페이",
  KAIA: "카이아",
  ONG: "온톨로지 가스",
  MLK: "밀크",
  KSM: "쿠사마",
  CTK: "컨텍",
  NFT: "에이피이앤에프티",
  SUN: "선",
  EGLD: "멀티버스X",
  MED: "메디블록",
  "1INCH": "1인치",
  BOBA: "보바",
  MINA: "미나",
  JOE: "트레이더조",
  BTT: "비트토렌트",
  GMT: "스테픈",
  APE: "에이프코인",
  XCN: "체인",
  FLR: "플레어",
  SFP: "세이프팔",
  USDT: "테더",
  USDC: "USD코인",
  DAI: "다이",
  FRAX: "프랙스",

  // 빗썸 추가 심볼들
  QTUM: "퀀텀",
  A: "에이토큰",
  ELF: "엘프",
  SNT: "스테이터스",
  CTXC: "코르텍스",
  CVC: "시빅",
  IOST: "아이오스",
  AMO: "아모",
  ORBS: "오브스",
  MIX: "믹스마블",
  CRO: "크로",
  CHR: "크로미아",
  FCT2: "팩토리오",
  MEV: "엠이브이",
  SXP: "스와이프",
  EL: "엘리시아",
  XPR: "프로톤",
  EGG: "에그",
  ARPA: "아르파",
  CTC: "씨티씨",
  APM: "에이피엠",
  AERGO: "아르고",
  EVZ: "이브지",
  AWE: "에이더블유이",
  BEL: "벨라",
  POLA: "폴라",
  ADP: "에이디피",
  DVI: "디브이아이",
  GHX: "지에이치엑스",
  CBK: "씨비케이",
  MVC: "엠브이씨",
  BLY: "블록시티",
  BIOT: "바이오패스포트",
  SOFI: "소피",
  GRACY: "그래시",
  OXT: "옥스타워",
  MAPO: "맵프로토콜",
  AQT: "에이큐티",
  WIKEN: "위켄",
  PUNDIX: "펀디엑스",
  SWAP: "트러스트스왑",

  // 추가 코인들 한국어 이름
  MNT: "맨틀",
  OMNI: "옴니 네트워크",
  PLUME: "플룸 네트워크",
  FLOCK: "플록",
  PROVE: "프루브",
  AVL: "아발론 랩스",
  IP: "스토리 프로토콜",
  SD: "스테이더",
  SIGN: "사인",
  SOON: "순",
  HOME: "홈코인",
  HFT: "해시플로우",
  ORDER: "오더리 네트워크",
  POLYX: "폴리메시",
  BMT: "버블 맵스",
  MERL: "멀린 체인",
  TOWNS: "타운스",
  REI: "레이 네트워크",
  BLUE: "블루핀",
  MOCA: "모카버스",
  ERA: "칼데라",
  OM: "만트라",
  NMR: "뉴머레어",
  ZTX: "제트엑스",
  ID: "스페이스 아이디",
  XPLA: "엑스플라",
  C: "체인베이스",
  CSPR: "캐스퍼",
  SONIC: "소닉",
  STX: "스택스",
  SPURS: "토트넘 팬토큰",
  USDS: "USDS",
  ZRC: "지르쿠이트",
  BFC: "비프로스트",
  BOA: "보사고라",
  GAME2: "게임빌드",
  FITFI: "스텝 앱",
  ASTR: "아스타",
  WAXL: "액셀러",
  REZ: "렌조",
  PEAQ: "피크",
  MBX: "마블렉스",
  OAS: "오아시스",
  PCI: "페이코인",
  CARV: "카브",
  PUFFER: "퍼퍼 파이낸스",
  GOAT: "고트",
  A8: "에인션트8",
  ARDR: "아더",

  // 새로 추가된 코인들 한국어 이름
  ATH: "에이셔",
  FORT: "포트",
  ACE: "퓨저니스트",
  WAL: "월러스",
  HAEDAL: "해달",
  H: "H",
  SYRUP: "시럽",
  PROMPT: "프롬프트",

  // 빗썸 API 추가 심볼들
  UOS: "울트라",
  SAND: "샌드박스",
  MANA: "디센트럴랜드",
  SUSHI: "스시스왑",
  CELR: "셀러",
  SLF: "셀프키",
  ALICE: "마이네이버앨리스",
  OGN: "오리진프로토콜",
  COTI: "코티",
  CAKE: "팬케이크스왑",
  BNT: "뱅코르",
  XVS: "비너스",
  CTSI: "카르테시",
  LPT: "라이브피어",
  RSR: "리저브라이츠",
  BAL: "밸런서",
  RLC: "아이엑스알엘씨",
  OBSR: "옵서버",
};
