// 바이낸스 코인들의 네트워크 정보
export const BINANCE_COIN_NETWORKS = {
  '1INCH': ['이더리움 (ERC-20)', 'BNB 체인', '폴리곤'],
  'AAVE': ['이더리움 (ERC-20)'],
  'ACE': ['Endurance (네이티브)'],
  'ACH': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'ACX': ['이더리움 (ERC-20)'],
  'ADA': ['카르다노 (네이티브)'],
  'AGLD': ['이더리움 (ERC-20)'],
  'ALGO': ['알고랜드 (네이티브)'],
  'ALICE': ['이더리움 (ERC-20)', 'BNB 체인', '솔라나'],
  'ALT': ['이더리움 (ERC-20)'],
  'AMP': ['이더리움 (ERC-20)'],
  'ANIME': ['이더리움 (ERC-20)', 'Arbitrum'],
  'ANKR': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'APE': ['이더리움 (ERC-20)'],
  'API3': ['이더리움 (ERC-20)'],
  'APT': ['앱토스 (네이티브)'],
  'AR': ['아위브 (네이티브)'],
  'ARB': ['이더리움 (ERC-20)'],
  'ARDR': ['아더 (네이티브)'],
  'ARK': ['ARK (네이티브)'],
  'ARKM': ['이더리움 (ERC-20)'],
  'ARPA': ['이더리움 (ERC-20)'],
  'ASTR': ['아스타 (네이티브)'],
  'ATOM': ['코스모스 (네이티브)'],
  'AUCTION': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'AUDIO': ['이더리움 (ERC-20)', '솔라나 (SPL)'],
  'AVAX': ['아발란체 (네이티브)'],
  'AXS': ['이더리움 (ERC-20)', 'Ronin (네이티브)'],
  'BAT': ['이더리움 (ERC-20)'],
  'BB': ['BounceBit (네이티브)'],
  'BCH': ['비트코인 캐시 (네이티브)'],
  'BEL': ['이더리움 (ERC-20)'],
  'BERA': ['Berachain (네이티브)'],
  'BICO': ['이더리움 (ERC-20)'],
  'BIGTIME': ['이더리움 (ERC-20)'],
  'BLUR': ['이더리움 (ERC-20)'],
  'BNB': ['BNB 체인 (네이티브)'],
  'BNT': ['이더리움 (ERC-20)'],
  'BONK': ['솔라나 (SPL)'],
  'BTC': ['비트코인 (네이티브)'],
  'C98': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)', '솔라나 (SPL)'],
  'CAKE': ['BNB 체인 (BEP-20)'],
  'CELO': ['셀로 (네이티브)'],
  'CELR': ['이더리움 (ERC-20)'],
  'CFX': ['컨플럭스 (네이티브)'],
  'CHR': ['이더리움 (ERC-20)'],
  'CHZ': ['이더리움 (ERC-20)', 'Chiliz Chain (네이티브)'],
  'CKB': ['너보스 네트워크 (네이티브)'],
  'COMP': ['이더리움 (ERC-20)'],
  'COOKIE': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'COS': ['BNB 체인 (BEP-2)', 'Contentos (네이티브)'],
  'COTI': ['COTI (네이티브)', '이더리움 (ERC-20)'],
  'COW': ['이더리움 (ERC-20)'],
  'CRV': ['이더리움 (ERC-20)'],
  'CTK': ['Shentu 체인 (네이티브)'],
  'CTSI': ['이더리움 (ERC-20)'],
  'CVC': ['이더리움 (ERC-20)'],
  'CYBER': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)', 'Optimism'],
  'DOGE': ['도지코인 (네이티브)'],
  'DOT': ['폴카닷 (네이티브)'],
  'DYDX': ['이더리움 (ERC-20)', 'dYdX 체인 (네이티브)'],
  'EDU': ['BNB 체인 (BEP-20)'],
  'EGLD': ['멀티버스엑스 (네이티브)'],
  'EIGEN': ['이더리움 (ERC-20)'],
  'ENA': ['이더리움 (ERC-20)'],
  'ENJ': ['이더리움 (ERC-20)'],
  'ENS': ['이더리움 (ERC-20)'],
  'ETC': ['이더리움 클래식 (네이티브)'],
  'ETH': ['이더리움 (네이티브)'],
  'ETHFI': ['이더리움 (ERC-20)'],
  'FET': ['Fetch.ai (네이티브)', '이더리움 (ERC-20)'],
  'FIDA': ['솔라나 (SPL)'],
  'FIL': ['파일코인 (네이티브)'],
  'FLOKI': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'FLOW': ['플로우 (네이티브)'],
  'FLUX': ['Flux (네이티브)'],
  'FXS': ['이더리움 (ERC-20)'],
  'GALA': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'GAS': ['네오 (NEO)'],
  'GLM': ['이더리움 (ERC-20)'],
  'GMT': ['솔라나 (SPL)', 'BNB 체인 (BEP-20)'],
  'GMX': ['Arbitrum', 'Avalanche'],
  'GNO': ['이더리움 (ERC-20)'],
  'GRT': ['이더리움 (ERC-20)'],
  'GTC': ['이더리움 (ERC-20)'],
  'HBAR': ['헤데라 (네이티브)'],
  'HFT': ['이더리움 (ERC-20)'],
  'HIGH': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'HIVE': ['하이브 (네이티브)'],
  'HOOK': ['BNB 체인 (BEP-20)'],
  'HUMA': ['이더리움 (ERC-20)'],
  'ICP': ['인터넷 컴퓨터 (네이티브)'],
  'ICX': ['아이콘 (네이티브)'],
  'ID': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'ILV': ['이더리움 (ERC-20)'],
  'IMX': ['이더리움 (ERC-20)'],
  'INJ': ['인젝티브 (네이티브)'],
  'IO': ['솔라나 (SPL)'],
  'IOST': ['IOST (네이티브)'],
  'IOTA': ['IOTA (네이티브)'],
  'IOTX': ['IoTeX (네이티브)', '이더리움 (ERC-20)'],
  'IQ': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)', 'Polygon'],
  'JASMY': ['이더리움 (ERC-20)'],
  'JOE': ['아발란체 (ARC-20)'],
  'JST': ['트론 (TRC-20)'],
  'JTO': ['솔라나 (SPL)'],
  'JUP': ['솔라나 (SPL)'],
  'KAIA': ['Kaia (네이티브)'],
  'KAVA': ['카바 (네이티브)'],
  'KNC': ['이더리움 (ERC-20)'],
  'KSM': ['쿠사마 (네이티브)'],
  'LA': ['이더리움 (ERC-20)'],
  'LDO': ['이더리움 (ERC-20)'],
  'LINK': ['이더리움 (ERC-20)'],
  'LISTA': ['BNB 체인 (BEP-20)'],
  'LPT': ['이더리움 (ERC-20)'],
  'LRC': ['이더리움 (ERC-20)'],
  'LSK': ['리스크 (네이티브)'],
  'MAGIC': ['이더리움 (ERC-20)', 'Arbitrum'],
  'MANA': ['이더리움 (ERC-20)'],
  'MANTA': ['이더리움 (ERC-20)', 'Manta Pacific (네이티브)'],
  'MASK': ['이더리움 (ERC-20)'],
  'MAV': ['이더리움 (ERC-20)', 'zkSync Era'],
  'MBL': ['온톨로지 (OEP-4)'],
  'METIS': ['이더리움 (ERC-20)'],
  'MINA': ['미나 프로토콜 (네이티브)'],
  'MTL': ['이더리움 (ERC-20)'],
  'NEAR': ['니어 프로토콜 (네이티브)'],
  'NEO': ['네오 (네이티브)'],
  'NMR': ['이더리움 (ERC-20)'],
  'OGN': ['이더리움 (ERC-20)'],
  'OM': ['이더리움 (ERC-20)'],
  'OMNI': ['이더리움 (ERC-20)'],
  'ONDO': ['이더리움 (ERC-20)'],
  'ONG': ['온톨로지 (네이티브)'],
  'ONT': ['온톨로지 (네이티브)'],
  'OP': ['이더리움 (ERC-20)'],
  'ORCA': ['솔라나 (SPL)'],
  'OSMO': ['오스모시스 (네이티브)'],
  'OXT': ['이더리움 (ERC-20)'],
  'PAXG': ['이더리움 (ERC-20)'],
  'PENDLE': ['이더리움 (ERC-20)', 'Arbitrum'],
  'PEPE': ['이더리움 (ERC-20)'],
  'POL': ['이더리움 (ERC-20)'],
  'POLYX': ['Polymesh (네이티브)'],
  'POWR': ['이더리움 (ERC-20)'],
  'PUNDIX': ['이더리움 (ERC-20)'],
  'PYR': ['이더리움 (ERC-20)', 'Polygon'],
  'PYTH': ['솔라나 (SPL)'],
  'QKC': ['QuarkChain (네이티브)'],
  'QTUM': ['퀀텀 (네이티브)'],
  'RAD': ['이더리움 (ERC-20)'],
  'RAY': ['솔라나 (SPL)'],
  'REI': ['REI Network (네이티브)'],
  'RENDER': ['이더리움 (ERC-20)', '솔라나 (SPL)'],
  'REQ': ['이더리움 (ERC-20)'],
  'REZ': ['이더리움 (ERC-20)'],
  'RLC': ['이더리움 (ERC-20)'],
  'RPL': ['이더리움 (ERC-20)'],
  'RSR': ['이더리움 (ERC-20)'],
  'RVN': ['레이븐코인 (네이티브)'],
  'SAND': ['이더리움 (ERC-20)', 'Polygon'],
  'SC': ['시아 (네이티브)'],
  'SEI': ['세이 (네이티브)'],
  'SFP': ['BNB 체인 (BEP-20)'],
  'SHIB': ['이더리움 (ERC-20)'],
  'SKL': ['이더리움 (ERC-20)'],
  'SNX': ['이더리움 (ERC-20)'],
  'SOL': ['솔라나 (네이티브)'],
  'SOLV': ['Arbitrum', 'Mantle', 'BNB 체인'],
  'SOPH': ['이더리움 (ERC-20)'],
  'STEEM': ['스팀 (네이티브)'],
  'STG': ['이더리움 (ERC-20)'],
  'STORJ': ['이더리움 (ERC-20)'],
  'STRAX': ['스트라티스 (네이티브)'],
  'STRK': ['이더리움 (ERC-20)'],
  'STX': ['스택스 (네이티브)'],
  'SUI': ['수이 (네이티브)'],
  'SUN': ['트론 (TRC-20)'],
  'SUSHI': ['이더리움 (ERC-20)'],
  'SXP': ['솔라 (네이티브)', '이더리움 (ERC-20)', 'BNB 체인 (BEP-20)'],
  'T': ['이더리움 (ERC-20)'],
  'TFUEL': ['쎄타 (네이티브)'],
  'THETA': ['쎄타 (네이티브)'],
  'TIA': ['셀레스티아 (네이티브)'],
  'TON': ['TON (네이티브)'],
  'TRUMP': ['이더리움 (ERC-20)'],
  'TRX': ['트론 (네이티브)'],
  'TURBO': ['이더리움 (ERC-20)'],
  'UMA': ['이더리움 (ERC-20)'],
  'UNI': ['이더리움 (ERC-20)'],
  'USDC': ['이더리움 (ERC-20)'], // 다수 체인 지원하지만 대표적인 것만
  'USDT': ['이더리움 (ERC-20)'], // 다수 체인 지원하지만 대표적인 것만
  'VANA': ['이더리움 (ERC-20)'],
  'VET': ['비체인 (네이티브)'],
  'VIRTUAL': ['이더리움 (ERC-20)'],
  'VTHO': ['비체인 (네이티브)'],
  'W': ['이더리움 (ERC-20)', '솔라나 (SPL)'],
  'WAXP': ['WAX (네이티브)'],
  'WIF': ['솔라나 (SPL)'],
  'WLD': ['이더리움 (ERC-20)', 'Optimism'],
  'WOO': ['이더리움 (ERC-20)', 'BNB 체인 (BEP-20)', 'Polygon', 'Avalanche'],
  'XAI': ['Arbitrum'],
  'XEC': ['이캐시 (네이티브)'],
  'XLM': ['스텔라 (네이티브)'],
  'XRP': ['XRP 레저 (네이티브)'],
  'XTZ': ['테조스 (네이티브)'],
  'XVS': ['BNB 체인 (BEP-20)'],
  'YFI': ['이더리움 (ERC-20)'],
  'YGG': ['이더리움 (ERC-20)'],
  'ZIL': ['질리카 (네이티브)'],
  'ZK': ['이더리움 (ERC-20)'],
  'ZRO': ['이더리움 (ERC-20)'],
  'ZRX': ['이더리움 (ERC-20)'],

  // 새로 추가된 코인들
  'MERL': ['비트코인 레이어 2 (네이티브)'],
  'AVNT': ['Base'],
  'AERO': ['Base'],
  'ATH': ['솔라나', '이더리움'],
  'AVAIL': ['Avail (네이티브)'],
  'AI16Z': ['솔라나 (SPL)'],
  'AVL': ['Avalon Labs 생태계'],
  'B3': ['Base (레이어 3)'],
  'BLUE': ['솔라나', 'PoW 블록체인'],
  'CARV': ['이더리움 (ERC-20)', 'Arbitrum', 'Base'],
  'DRIFT': ['솔라나 (SPL)'],
  'EPT': ['이더리움', 'BNB 체인'],
  'F': ['이더리움 (ERC-20)', 'Base', 'Blast'],
  'FLOCK': ['BNB 체인 (BSC)'],
  'G': ['PlayBlock (네이티브)'],
  'GOAT': ['비트코인 ZK 롤업'],
  'GRASS': ['솔라나 (레이어 2)'],
  'H': ['이더리움 (레이어 2)', 'Polygon CDK'],
  'MEW': ['솔라나 (SPL)'],
  'MOODENG': ['솔라나 (SPL)'],
  'OBT': ['이더리움', '멀티체인'],
  'ORDER': ['NEAR', '멀티체인'],
  'PEFFUR': ['이더리움 (ERC-20)'],
  'PEAQ': ['peaq (네이티브)'],
  'POKT': ['Pocket Network (네이티브)'],
  'PROMPT': ['AI Wayfinder Ecosystem'],
  'PROVE': ['이더리움 (ERC-20)'],
  'PUMPBTC': ['BNB 체인 (BSC)', '이더리움'],
  'RESOLV': ['Immutable'],
  'SAFE': ['솔라나 포크', '이더리움 (ERC-20)'],
  'SD': ['이더리움 (ERC-20)'],
  'SUNDOG': ['트론 (TRC)'],
  'TAIKO': ['이더리움 레이어 2 (ZK-Rollup)'],
  'TOWNS': ['이더리움 (ERC-20)', 'Base'],
  'XTER': ['Xterio (네이티브)'],
  'ZETA': ['ZetaChain (네이티브)'],
  'ZRC': ['이더리움 (레이어 2)', 'ZK-Rollup'],

  // 추가 코인들 (두 번째 배치)
  'EUL': ['이더리움 (ERC-20)'],
  'ACS': ['솔라나 (SPL)', '스타크넷'],
  'AERGO': ['하이브리드 블록체인 (자체 메인넷)', '이더리움'],
  'AHT': ['자체 블록체인'],
  'AKT': ['코스모스 (Cosmos)'],
  'BFC': ['자체 메인넷 (EVM 호환)'],
  'BORA': ['클레이튼 (Klaytn)'],
  'BOUNTY': ['스마트 컨트랙트 플랫폼'],
  'BRETT': ['Base (이더리움 레이어 2)'],
  'CBK': ['이더리움'],
  'CRO': ['크로노스 (Cronos)'],
  'CTC': ['자체 메인넷 (PoW + PoS)'],
  'DEEP': ['거래소 토큰'],
  'DKA': ['이더리움 (ERC-20)'],
  'GRS': ['그로스톨코인 (네이티브)'],
  'HUNT': ['이더리움 (ERC-20)', '폴리곤'],
  'MLK': ['클레이튼 (Klaytn)'],
  'MVL': ['이더리움 (ERC-20)'],
  'ORBS': ['이더리움 (ERC-20)', '자체 메인넷'],
  'SNT': ['이더리움 (ERC-20)'],
  'WAVES': ['웨이브스 (네이티브)'],
  'AQT': ['이더리움'],
  'BEAM': ['자체 블록체인', '아발란체'],
  'BLAST': ['이더리움 (L2)', '솔라나'],
  'BSV': ['비트코인'],
  'BTT': ['트론'],
  'ELF': ['자체 블록체인'],
  'FCT2': ['자체 블록체인', '이더리움'],
  'GAME2': ['자체 블록체인'],
  'HP': ['BNB', '자체 블록체인 (L1)'],
  'IP': ['자체 블록체인'],
  'LWA': ['수이 (Sui)'],
  'MED': ['자체 블록체인', '이더리움'],
  'META': ['바이낸스 스마트 체인 (BSC)'],
  'MNT': ['이더리움 (L2)'],
  'MOC': ['이더리움'],
  'MOCA': ['이더리움', '자체 블록체인'],
  'NCT': ['폴리곤'],
  'OBSR': ['옵저버 (자체 메인넷)'],
  'PUFFER': ['이더리움'],
  'SKY': ['자체 블록체인 (Skycoin)'],
  'SONIC': ['솔라나 (L2)'],
  'SOON': ['이더리움'],
  'SPURS': ['칠리즈 (Chiliz)'],
  'SWELL': ['이더리움'],
  'TOKAMAK': ['이더리움'],
  'TT': ['자체 블록체인'],
  'USDS': ['스텔라'],
  'UXLINK': ['이더리움 (L2)', '솔라나'],
  'WAL': ['이더리움']
};

// 네트워크별 색상 및 스타일
export const NETWORK_STYLES = {
  '이더리움': { color: 'bg-blue-500', text: 'text-white', shortName: 'ETH' },
  'BNB': { color: 'bg-yellow-500', text: 'text-black', shortName: 'BNB' },
  '솔라나': { color: 'bg-purple-500', text: 'text-white', shortName: 'SOL' },
  '비트코인': { color: 'bg-orange-500', text: 'text-white', shortName: 'BTC' },
  '폴리곤': { color: 'bg-purple-600', text: 'text-white', shortName: 'MATIC' },
  'Arbitrum': { color: 'bg-blue-600', text: 'text-white', shortName: 'ARB' },
  'Avalanche': { color: 'bg-red-500', text: 'text-white', shortName: 'AVAX' },
  '트론': { color: 'bg-red-600', text: 'text-white', shortName: 'TRX' },
  'Optimism': { color: 'bg-red-400', text: 'text-white', shortName: 'OP' },
  'Base': { color: 'bg-blue-400', text: 'text-white', shortName: 'BASE' },
  'NEAR': { color: 'bg-green-500', text: 'text-white', shortName: 'NEAR' },
  'ZK-Rollup': { color: 'bg-indigo-500', text: 'text-white', shortName: 'ZK' },
  'L2': { color: 'bg-violet-500', text: 'text-white', shortName: 'L2' },
  'AI': { color: 'bg-cyan-500', text: 'text-white', shortName: 'AI' },
  '코스모스': { color: 'bg-blue-700', text: 'text-white', shortName: 'ATOM' },
  '클레이튼': { color: 'bg-red-500', text: 'text-white', shortName: 'KLAY' },
  '크로노스': { color: 'bg-blue-800', text: 'text-white', shortName: 'CRO' },
  '웨이브스': { color: 'bg-blue-300', text: 'text-white', shortName: 'WAVES' },
  '아발란체': { color: 'bg-red-500', text: 'text-white', shortName: 'AVAX' },
  '수이': { color: 'bg-cyan-600', text: 'text-white', shortName: 'SUI' },
  '칠리즈': { color: 'bg-red-700', text: 'text-white', shortName: 'CHZ' },
  '스텔라': { color: 'bg-black', text: 'text-white', shortName: 'XLM' },
  '스타크넷': { color: 'bg-purple-700', text: 'text-white', shortName: 'STRK' },
  '자체': { color: 'bg-emerald-500', text: 'text-white', shortName: '독립' },
  '기타': { color: 'bg-gray-500', text: 'text-white', shortName: '기타' }
};

// 네트워크 이름 정규화 함수
export const normalizeNetworkName = (network: string): string => {
  if (network.includes('이더리움')) return '이더리움';
  if (network.includes('BNB') || network.includes('바이낸스') || network.includes('BSC')) return 'BNB';
  if (network.includes('솔라나')) return '솔라나';
  if (network.includes('비트코인')) return '비트코인';
  if (network.includes('폴리곤') || network.includes('Polygon')) return '폴리곤';
  if (network.includes('Arbitrum')) return 'Arbitrum';
  if (network.includes('Avalanche') || network.includes('아발란체')) return '아발란체';
  if (network.includes('트론')) return '트론';
  if (network.includes('Optimism')) return 'Optimism';
  if (network.includes('Base')) return 'Base';
  if (network.includes('NEAR')) return 'NEAR';
  if (network.includes('ZK') || network.includes('영지식')) return 'ZK-Rollup';
  if (network.includes('레이어 2') || network.includes('L2')) return 'L2';
  if (network.includes('AI') || network.includes('인공지능')) return 'AI';
  if (network.includes('코스모스') || network.includes('Cosmos')) return '코스모스';
  if (network.includes('클레이튼') || network.includes('Klaytn')) return '클레이튼';
  if (network.includes('크로노스') || network.includes('Cronos')) return '크로노스';
  if (network.includes('웨이브스') || network.includes('Waves')) return '웨이브스';
  if (network.includes('수이') || network.includes('Sui')) return '수이';
  if (network.includes('칠리즈') || network.includes('Chiliz')) return '칠리즈';
  if (network.includes('스텔라') || network.includes('Stellar')) return '스텔라';
  if (network.includes('스타크넷') || network.includes('Starknet')) return '스타크넷';
  if (network.includes('자체') || network.includes('네이티브') || network.includes('메인넷')) return '자체';
  return '기타';
};

// 코인의 주요 네트워크 반환
export const getCoinMainNetwork = (symbol: string): string => {
  const networks = BINANCE_COIN_NETWORKS[symbol.toUpperCase() as keyof typeof BINANCE_COIN_NETWORKS];
  if (!networks || networks.length === 0) return '기타';
  
  // 첫 번째 네트워크를 주요 네트워크로 사용
  return normalizeNetworkName(networks[0]);
};