export const CRYPTO_SECTORS: { [key: string]: string } = {
  // L1 블록체인
  BTC: "가치저장/P2P결제",
  ETH: "L1/스마트컨트랙트",
  BNB: "L1/생태계유틸리티",
  SOL: "L1/고성능",
  ADA: "L1/학술기반PoS",
  AVAX: "L1/서브넷",
  DOT: "인터체인/파라체인허브",
  TRX: "L1/콘텐츠&결제",
  TON: "L1/소셜네트워크",
  NEAR: "L1/샤딩",
  ICP: "L1/분산형클라우드",
  ATOM: "인터체인/IBC허브",
  APT: "L1/Move언어",
  SUI: "L1/Move언어(자산중심)",
  HBAR: "L1/해시그래프(기업용)",
  ALGO: "L1/순수지분증명(PPoS)",
  CFX: "L1/Tree-Graph(중국)",
  KAIA: "L1/통합(클레이튼+핀시아)",
  SEI: "L1/트레이딩최적화",
  KLAY: "L1/카카오(KAIA에통합)",
  WAVES: "L1/Web3앱플랫폼",
  NEO: "L1/디지털자산(중국)",
  EOS: "L1/DPoS",
  QTUM: "L1/하이브리드(UTXO+EVM)",
  ONT: "L1/탈중앙화신원(DID)",
  ZIL: "L1/샤딩",
  FLOW: "L1/NFT&게임",
  ROSE: "L1/프라이버시&데이터",
  ONE: "L1/샤딩&크로스체인",
  EGLD: "L1/샤딩(구Elrond)",
  FTM: "L1/DAG기반",
  CELO: "L1/모바일금융",
  MINA: "L1/경량블록체인(zk-SNARK)",
  BEAM: "L1/GameFi네트워크",
  CORE: "L1/SatoshiPlus합의",
  BSV: "L1/비트코인포크",
  ETC: "L1/이더리움오리지널(PoW)",
  INJ: "L1/DeFi최적화",
  BB: "L1/비트코인리스테이킹",
  IOST: "L1/PoB합의",
  ORBS: "L1/하이브리드(실행레이어)",
  AERGO: "L1/하이브리드(기업용)",
  CRO: "L1/EVM호환(Crypto.com)",
  CHR: "L1/관계형블록체인",
  CSPR: "L1/PoS(기업용)",
  BOA: "L1/DAO기반",
  OAS: "L1/게임최적화",
  XPLA: "L1/게임&콘텐츠(Com2uS)",
  REI: "L1/경량EVM",
  ARDR: "L1/부모-자식체인(BaaS)",
  ACE: "GameFi/L1(Endurance)",
  UOS: "GameFi/PC게임유통",

  // L2 & 확장성
  ARB: "L2/옵티미스틱롤업",
  OP: "L2/옵티미스틱롤업",
  MATIC: "L2/PoS사이드체인&플라즈마",
  POL: "L2/생태계레이어",
  STRK: "L2/ZK롤업(STARK)",
  METIS: "L2/옵티미스틱롤업(하이브리드)",
  BOBA: "L2/옵티미스틱롤업(멀티체인)",
  LRC: "L2/ZK롤업(DEX특화)",
  BLAST: "L2/옵티미스틱롤업(네이티브이자수익)",
  SCROLL: "L2/ZK롤업(EVM호환)",
  SCR: "L2/ZK롤업(프라이버시)",
  LINEA: "L2/ZK롤업(EVM호환)",
  ZK: "L2/ZK롤업",
  TAIKO: "L2/ZK롤업(Based)",
  MNT: "L2/모듈러(옵티미스틱)",
  STX: "L2/비트코인레이어",
  ZRC: "L2/ZK롤업",
  MANTA: "L2/모듈러(ZK&프라이버시)",
  MERL: "L2/비트코인레이어",

  // 2024년 신규 메인 코인들
  HYPE: "PerpDEX/L1(자체체인)",
  VIRTUAL: "AI/에이전트생태계",
  MOVE: "L2/모듈러(Move언어)",
  ME: "NFT/마켓플레이스(매직에덴)",
  PENGU: "NFT/커뮤니티(PudgyPenguins)",
  USUAL: "RWA/스테이블코인(USD0)",
  VELODROME: "DEX/AMM(Optimism)",
  EIGEN: "리스테이킹/LRT",
  ONDO: "RWA/토큰화증권",
  ETHFI: "리스테이킹/LRT",
  PUFFER: "리스테이킹/LRT",
  ENA: "스테이블코인/합성달러(USDe)",
  MORPHO: "DeFi/렌딩최적화",
  AERO: "DEX/AMM(Base)",
  VELO: "DEX/AMM(Optimism)",

  // AI 에이전트 생태계
  ZEREBRO: "AI/콘텐츠생성&분석",
  AI16Z: "AI/탈중앙화AI트레이딩펀드",
  VIRTUALS: "AI/에이전트생성프로토콜",
  AIXBT: "AI/시장분석&트렌드탐지",
  ACT: "AI/선지자AI",

  // 밈 코인들
  DOGE: "밈/오리지널(PoW)",
  SHIB: "밈/이더리움생태계(시바리움)",
  PEPE: "밈/이더리움(페페더프로그)",
  FLOKI: "밈/멀티체인(유틸리티지향)",
  BONK: "밈/솔라나(커뮤니티코인)",
  WIF: "밈/솔라나(모자쓴개)",
  POPCAT: "밈/솔라나(팝캣)",
  MEW: "밈/솔라나(고양이테마)",
  BRETT: "밈/베이스체인",
  RETARDIO: "밈/커뮤니티",
  CHILLGUY: "밈/커뮤니티",
  MOODENG: "밈/커뮤니티",
  PNUT: "밈/커뮤니티",
  GOAT: "밈/커뮤니티",
  NEIRO: "밈/커뮤니티",
  SPX: "밈/커뮤니티",
  TURBO: "밈/AI생성",
  FARTCOIN: "밈/커뮤니티",
  PONKE: "밈/솔라나(겜블러원숭이)",
  SUNDOG: "밈/커뮤니티",
  ANIME: "밈/콘텐츠(애니메이션)",

  // DeFi 프로토콜
  UNI: "DEX/AMM(이더리움)",
  AAVE: "DeFi/렌딩",
  COMP: "DeFi/렌딩",
  SUSHI: "DEX/AMM(멀티체인)",
  CRV: "DEX/AMM(스테이블스왑)",
  MKR: "DeFi/CDP(DAI발행)",
  SNX: "DeFi/파생상품(신세틱스)",
  YFI: "DeFi/수익애그리게이터",
  BAL: "DEX/AMM(유동성풀)",
  CAKE: "DEX/AMM(BNB체인)",
  DYDX: "DEX/파생상품(Perp)",
  GMX: "DEX/파생상품(Perp,멀티체인)",
  JOE: "DEX/AMM(Avalanche)",
  PENDLE: "DeFi/수익토큰화(YT/PT)",
  "1INCH": "DEX/애그리게이터",
  JUP: "DEX/애그리게이터(솔라나)",
  RAY: "DEX/AMM(솔라나)",
  ORCA: "DEX/AMM(솔라나)",
  F: "DeFi/파생상품",
  SPK: "DeFi/유동성",
  HUMA: "DeFi/RWA(토큰화신용)",
  CTC: "DeFi/신용(Creditcoin)",
  SXT: "DeFi/자산관리",
  ZRX: "DEX/유동성프로토콜",
  KNC: "DEX/애그리게이터",
  COW: "DEX/MEV방지애그리게이터",
  MEV: "DeFi/MEV솔루션",
  WOO: "CEX/DEX유동성네트워크",
  XVS: "DeFi/렌딩(BNB체인)",
  BNT: "DEX/AMM",
  HFT: "DEX/애그리게이터",
  OSMO: "DEX/AMM(코스모스)",
  SYRUP: "DeFi/대출",
  HAEDAL: "DeFi/유동성스테이킹",
  AVL: "DeFi/비트코인",
  PUMP: "DEX/런치패드",
  RDNT: "DeFi/렌딩(멀티체인)",

  // 스테이킹/LST & LRT
  LDO: "LST/리퀴드스테이킹(Lido)",
  RPL: "LST/리퀴드스테이킹(RocketPool)",
  JTO: "LST/솔라나MEV스테이킹(Jito)",
  SWELL: "LST&LRT/리퀴드(리)스테이킹",
  REZ: "LRT/리스테이킹(Renzo)",
  LISTA: "CDP&LRT/스테이블코인&리스테이킹",
  BABY: "LST/비트코인스테이킹(Babylon)",
  SD: "LST/멀티체인리퀴드스테이킹(Stader)",
  SWISE: "LST/리퀴드스테이킹(StakeWise)",
  FRXETH: "LST/Frax생태계ETH",
  STETH: "LST/Lido의ETH토큰",
  RETH: "LST/RocketPool의ETH토큰",

  // 오라클/데이터
  LINK: "오라클",
  BAND: "오라클",
  API3: "오라클",
  PYTH: "오라클",
  UMA: "오라클",
  REP: "오라클",
  RED: "오라클",

  // 스테이블코인
  USDT: "스테이블코인",
  USDC: "스테이블코인",
  DAI: "스테이블코인",
  FRAX: "스테이블코인",
  BUSD: "스테이블코인",
  TUSD: "스테이블코인",
  USDS: "스테이블코인",
  USD1: "RWA/스테이블",
  FXS: "RWA/스테이블",
  RSR: "스테이블코인",

  // GameFi, NFT, Metaverse & M2E
  AXS: "GameFi/메타버스",
  SAND: "GameFi/메타버스",
  MANA: "GameFi/메타버스",
  ENJ: "GameFi/NFT",
  GALA: "GameFi/메타버스",
  IMX: "GameFi/NFT",
  BLUR: "GameFi/NFT",
  MAGIC: "GameFi/메타버스",
  APE: "GameFi/NFT",
  GMT: "M2E/피트니스",
  YGG: "게이밍 길드",
  ALICE: "GameFi/메타버스",
  RON: "GameFi/L1",
  BIGTIME: "GameFi/MMO",
  ILV: "GameFi/메타버스",
  WAXP: "GameFi/NFT",
  XAI: "GameFi/L3",
  AGLD: "GameFi/NFT",
  EPT: "AI/소셜 게이밍",
  TDROP: "NFT",
  MOC: "메타버스/GameFi",
  GRND: "M2E",
  NXPC: "메타버스",
  MBX: "GameFi/퍼블리싱",
  A8: "게이밍 길드",
  SIGN: "GameFi/플랫폼",
  MOCA: "GameFi/NFT",
  GAME2: "GameFi/NFT",
  FITFI: "M2E/피트니스",
  ZTX: "GameFi/메타버스",
  HIGH: "메타버스·커머스",
  DVI: "기타",
  PYR: "기타",

  // AI & 데이터
  WLD: "AI/생체인증ID(Worldcoin)",
  FET: "AI/자율에이전트(Fetch.ai)",
  AGIX: "AI/마켓플레이스(SingularityNET)",
  RENDER: "DePIN/분산GPU렌더링",
  GRT: "인프라/블록체인인덱싱(TheGraph)",
  OCEAN: "AI/데이터마켓플레이스",
  TAO: "AI/분산머신러닝(Bittensor)",
  IO: "DePIN/분산GPU클라우드(io.net)",
  ARKM: "AI/온체인분석(Arkham)",
  AIOZ: "DePIN/분산CDN",
  LA: "AI/데이터수익화(LayerAI)",
  SHELL: "AI/프로토콜",
  STAT: "AI/데이터분석",
  AWE: "AI/DePIN",
  NMR: "AI/헤지펀드&예측(Numeraire)",
  PROMPT: "AI/콘텐츠생성",
  FLOCK: "AI/분산모델트레이닝",
  IOTA: "IoT/분산원장(Tangle)",
  CTXC: "AI/온체인AI모델(Cortex)",
  JASMY: "IoT/데이터주권",
  BMT: "데이터/분석",
  C: "AI/데이터",

  // 스토리지
  FIL: "스토리지",
  AR: "스토리지",
  STORJ: "스토리지",
  BTT: "스토리지/파일공유",
  SC: "스토리지",
  WAL: "스토리지/인프라",

  // 한국 프로젝트
  ICX: "한국/L1",
  BORA: "한국/콘텐츠",
  TEMCO: "한국/공급망",
  META: "한국/DID",
  MVL: "한국/모빌리티",
  MED: "한국/DID",
  MLK: "한국/콘텐츠",
  HUNT: "한국/콘텐츠",
  WEMIX: "한국/게임",
  SSX: "한국/콘텐츠",
  MBL: "한국/콘텐츠",
  BFC: "한국/L1",
  TOKAMAK: "한국/L2",

  // 결제 & 송금
  XRP: "결제/송금",
  LTC: "결제/기축",
  BCH: "결제/기축",
  XLM: "결제/송금",
  DASH: "결제/송금",
  ACH: "결제/송금",
  XCN: "결제/송금",
  REQ: "결제/인보이스",
  XYO: "위치 오라클/결제",
  AMP: "결제 담보 토큰",
  MTL: "결제/라이선스",
  XPR: "결제/신원인증",
  PUNDIX: "결제/송금",
  SXP: "결제/송금",
  PCI: "결제/상거래",
  COTI: "결제/송금",

  // 인프라, DePIN, 프라이버시
  VET: "물류/공급망",
  THETA: "인프라/미디어",
  BAT: "광고/브라우저",
  LPT: "인프라/미디어",
  OBT: "인프라/브릿지",
  RAD: "인프라/개발자 도구",
  VANA: "DePIN/데이터",
  ZEC: "프라이버시",
  XMR: "프라이버시",
  EVZ: "프라이버시/DeFi",
  CTK: "블록체인 보안",
  ANKR: "인프라/스테이킹",
  AKT: "분산 컴퓨팅/DePIN",
  RLC: "인프라/컴퓨팅",
  GLM: "분산 컴퓨팅/DePIN",
  POKT: "인프라/노드",
  FLUX: "인프라/분산컴퓨팅",
  ATH: "DePIN/GPU",
  PEAQ: "DePIN/머신 경제",
  ALT: "롤업 인프라/애그리게이션",
  ERA: "롤업 인프라/RaaS",
  SOON: "인프라/롤업",
  PROVE: "인프라/ZK",
  BICO: "인프라/지갑·레저",
  FORT: "보안/인프라",
  T: "프라이버시",
  ARPA: "프라이버시",
  OXT: "프라이버시",
  OBSR: "프라이버시",
  SCRT: "Cosmos/프라이버시",
  TFUEL: "인프라/미디어",

  // 소셜 & DAO
  ACS: "소셜/콘텐츠 수익화",
  GTC: "DAO/공공재 펀딩",
  KERNEL: "DAO/커뮤니티",
  MASK: "소셜/아이덴티티",
  ENS: "소셜/아이덴티티",
  LENS: "소셜/아이덴티티",
  AUDIO: "음악 스트리밍/콘텐츠",
  COS: "콘텐츠 플랫폼/소셜",
  HIVE: "소셜/아이덴티티",
  STEEM: "소셜/아이덴티티",
  SNT: "소셜/아이덴티티",
  CVC: "소셜/아이덴티티",
  AMO: "소셜/아이덴티티",
  TOWNS: "소셜/커뮤니티",
  ID: "소셜/아이덴티티",
  DAO: "DAO 툴링/거버넌스",
  SAFE: "금고/멀티시그",
  GNO: "DAO/멀티시그·DeFi",
  HOOK: "교육·소셜·게이미피케이션",
  EDU: "에듀테크/콘텐츠",
  IQ: "콘텐츠/지식플랫폼",
  OGN: "콘텐츠/플랫폼",
  IP: "IP/콘텐츠",
  LIVEPEER: "인프라/미디어",

  // 인터체인/브릿지
  KSM: "인터체인",
  ZRO: "인터체인",
  STG: "인터체인",
  W: "인터체인/브릿지",
  CELR: "인터체인/브릿지",
  REN: "인터체인/브릿지",
  OMNI: "인터체인",
  MAPO: "인터체인",
  ASTR: "L1/인터체인",
  WAXL: "인터체인/브릿지",

  // RWA (실물자산)
  POLYX: "RWA/증권토큰",
  PLUME: "RWA/디파이",
  OM: "RWA/디파이",
  SOLV: "RWA/디파이",
  HOME: "RWA/스테이블",

  // 기타
  ES: "L2/SVM롤업(이클립스)",
  HYPER: "L2/비트코인(네이티브수익)",
  A: "기타/테스트",
  MIX: "GameFi/플랫폼(믹스마블)",
  FCT2: "인프라/전자계약(피르마체인)",
  EL: "RWA/부동산디지털화(엘리시아)",
  EGG: "밈/솔라나",
  APM: "결제/B2B(apM코인)",
  BEL: "DeFi/수익애그리게이터(벨라)",
  POLA: "인프라/지식공유(폴라리스쉐어)",
  ADP: "콘텐츠/보상플랫폼(어댑터)",
  GHX: "DePIN/GPU공유(게이머해시)",
  CBK: "커뮤니티/리워드(코박토큰)",
  MVC: "결제/마일리지통합(마일벌스)",
  BLY: "RWA/농수산물유통(블로서리)",
  BIOT: "DID/의료데이터(바이오패스포트)",
  SOFI: "DeFi/소셜트레이딩(RAI파이낸스)",
  GRACY: "뷰티/커뮤니티(그레이시)",
  AQT: "RWA/IP거래(알파쿼크)",
  WIKEN: "스포츠/커리어관리(위드)",
  SWAP: "DeFi/런치패드(트러스트스왑)",
  DCR: "거버넌스/하이브리드PoW+PoS",
  POWR: "DePIN/P2P에너지거래",
  POLY: "RWA/증권형토큰(폴리매쓰)",
  SPURS: "팬토큰/스포츠(토트넘훗스퍼)",
  GAS: "L1/유틸리티(NEO)",
  ONG: "L1/유틸리티(Ontology)",
  VTHO: "L1/유틸리티(VeChain)",
  GRASS: "DePIN/대역폭공유",
  DRIFT: "DEX/파생상품(솔라나)",
  ZETA: "DEX/파생상품(솔라나)",
  AVAIL: "모듈러/DA레이어",
  TIA: "모듈러/DA레이어(셀레스티아)",
  CARV: "GameFi/DID&데이터",
  SONIC: "L1/게이밍SVM",
  LAYER: "L2/비트코인(솔레이어)",
  ORDER: "인프라/옴니체인유동성",
  RSS3: "인프라/정보피드",
  SLF: "DID/지갑",
  KEY: "DID/신원인증(SelfKey)",
  SFP: "인프라/지갑(세이프팔)",
  C98: "DeFi/게이트웨이(Coin98)",
  ELF: "L1/클라우드컴퓨팅",
  BLUE: "DEX/파생상품(블루핀)",

  // --- 코스모스 생태계 ---
  JUNO: "Cosmos/스마트컨트랙트",
  EVMOS: "Cosmos/EVM호환",
  LUNA: "Cosmos/스테이블(구Terra)",
  UST: "Cosmos/스테이블(구Terra)",
  MIR: "Cosmos/합성자산(미러 프로토콜)",
  ANC: "Cosmos/렌딩(앵커 프로토콜)",
};
