// 암호화폐 섹터 분류
export const CRYPTO_SECTORS: { [key: string]: string } = {
  // L1 블록체인
  BTC: "결제/기축",
  ETH: "L1",
  BNB: "L1",
  SOL: "L1",
  ADA: "L1",
  AVAX: "L1",
  DOT: "인터체인",
  TRX: "L1",
  TON: "L1",
  NEAR: "L1",
  ICP: "L1",
  ATOM: "인터체인",
  APT: "L1",
  SUI: "L1",
  HBAR: "L1",
  ALGO: "L1",
  CFX: "L1",
  KAIA: "L1",
  SEI: "L1",
  KLAY: "L1",
  WAVES: "L1",
  NEO: "L1",
  EOS: "L1",
  QTUM: "L1",
  ONT: "L1",
  ZIL: "L1",
  FLOW: "L1/특화",
  ROSE: "L1/특화",
  ONE: "L1",
  EGLD: "L1",
  FTM: "L1",
  CELO: "L1",
  MINA: "L1/특화",
  BEAM: "L1/특화",
  CORE: "L1",
  BSV: "L1/특화",
  ETC: "L1",

  // L2 & 확장성
  ARB: "L2",
  OP: "L2",
  MATIC: "L2",
  POL: "L2",
  STRK: "L2/ZK",
  METIS: "L2",
  BOBA: "L2",
  LRC: "L2/ZK",
  BLAST: "L2",
  SCROLL: "L2/ZK",
  SCR: "L2/ZK",
  LINEA: "L2/ZK",
  ZK: "L2/ZK",
  TAIKO: "L2/ZK",

  // 2024년 신규 메인 코인들
  HYPE: "L2/SVM 롤업",
  VIRTUAL: "AI·에이전트 생태",
  MOVE: "L2/멀티체인 인프라",
  ME: "NFT 마켓플레이스",
  PENGU: "밈·커뮤니티",
  USUAL: "RWA/스테이블",
  VELODROME: "AMM/유동성",
  EIGEN: "LRT/리스티킹",
  ONDO: "RWA/유동성 인프라",
  ETHFI: "LRT/리스티킹",
  PUFFER: "LSD/LST 디파이",
  ENA: "RWA/스테이블",
  MORPHO: "렌딩",
  AERO: "DEX/AMM",
  VELO: "DEX/AMM",

  // AI 에이전트 생태계
  ZEREBRO: "AI·에이전트 생태",
  AI16Z: "AI·에이전트 생태",
  VIRTUALS: "AI·에이전트 생태",
  AIXBT: "AI·에이전트 생태",
  ACT: "AI·에이전트 생태",

  // 밈 코인들
  DOGE: "밈/커뮤니티",
  SHIB: "밈/커뮤니티",
  PEPE: "밈/커뮤니티",
  FLOKI: "밈/커뮤니티",
  BONK: "밈/커뮤니티",
  WIF: "밈/커뮤니티",
  POPCAT: "밈/커뮤니티",
  MEW: "밈/커뮤니티",
  BRETT: "밈/커뮤니티",
  RETARDIO: "밈·커뮤니티",
  CHILLGUY: "밈·커뮤니티",
  MOODENG: "밈·커뮤니티",
  PNUT: "밈·커뮤니티",
  GOAT: "밈·커뮤니티",
  NEIRO: "밈·커뮤니티",
  SPX: "밈·커뮤니티",
  TURBO: "밈·커뮤니티",
  FARTCOIN: "밈·커뮤니티",
  PONKE: "밈/커뮤니티",
  SUNDOG: "밈·커뮤니티",
  ANIME: "밈/콘텐츠",

  // DeFi 프로토콜
  UNI: "DEX/AMM",
  AAVE: "렌딩",
  COMP: "렌딩",
  SUSHI: "DEX/AMM",
  CRV: "DEX/AMM",
  MKR: "렌딩",
  SNX: "파생/Perp",
  YFI: "수익토큰화",
  BAL: "DEX/AMM",
  CAKE: "DEX/AMM",
  DYDX: "파생/Perp",
  GMX: "파생/Perp",
  JOE: "DEX/AMM",
  PENDLE: "수익토큰화",
  "1INCH": "DEX/애그리게이션",
  JUP: "DEX/애그리게이션",
  RAY: "DEX/AMM",
  ORCA: "DEX/AMM",

  // 스테이킹/LST
  LDO: "스테이킹/LST",
  RPL: "스테이킹/LST",
  JTO: "LSD/LST 디파이",

  // 오라클/데이터
  LINK: "오라클",
  BAND: "오라클",
  API3: "오라클",
  PYTH: "오라클",
  UMA: "오라클",

  // 스테이블코인
  USDT: "스테이블코인",
  USDC: "스테이블코인",
  DAI: "스테이블코인",
  FRAX: "스테이블코인",
  BUSD: "스테이블코인",
  TUSD: "스테이블코인",
  USDS: "스테이블코인",
  USD1: "RWA/스테이블",
  FXS: "RWA/스테이블",

  // GameFi/NFT
  AXS: "GameFi/메타버스",
  SAND: "GameFi/메타버스",
  MANA: "GameFi/메타버스",
  ENJ: "GameFi/NFT",
  GALA: "GameFi/메타버스",
  IMX: "GameFi/NFT",
  BLUR: "GameFi/NFT",
  MAGIC: "GameFi/메타버스",
  APE: "GameFi/NFT",
  GMT: "M2E/피트니스",
  YGG: "게이밍 길드",
  ALICE: "GameFi/메타버스",
  RON: "GameFi/L1",
  BIGTIME: "GameFi/MMO",
  ILV: "GameFi/메타버스",
  WAXP: "GameFi/NFT",
  XAI: "게임 퍼블리싱",
  AGLD: "GameFi/NFT",

  // AI/데이터
  WLD: "AI/데이터",
  FET: "AI/데이터",
  AGIX: "AI/데이터",
  RENDER: "AI/데이터",
  GRT: "인프라/인덱싱",
  OCEAN: "AI/데이터",
  TAO: "AI/데이터",
  IO: "AI/데이터",
  ARKM: "AI/데이터",
  AIOZ: "AI/데이터",
  LA: "AI/INFRASTRUCTURE",
  SHELL: "AI",

  // 스토리지
  FIL: "스토리지",
  AR: "스토리지",
  STORJ: "스토리지",
  BTT: "스토리지/파일공유",
  SC: "스토리지",

  // 한국 프로젝트
  ICX: "한국/L1",
  BORA: "한국/콘텐츠",
  TEMCO: "한국/공급망",
  META: "한국/DID",
  MVL: "한국/모빌리티",
  MED: "한국/DID",
  MLK: "한국/콘텐츠",
  HUNT: "한국/콘텐츠",
  WEMIX: "한국/게임",
  SSX: "한국/콘텐츠",
  MBL: "한국/콘텐츠",
  BFC: "한국/L1",
  TOKAMAK: "한국/L2",

  // 기타 알트코인
  XRP: "결제/송금",
  LTC: "결제/기축",
  BCH: "결제/기축",
  VET: "물류/공급망",
  THETA: "인프라/미디어",
  BAT: "광고/브라우저",
  ZRX: "DEX/프로토콜",
  KNC: "DEX/애그리게이션",
  REN: "인터체인/브릿지",
  LPT: "인프라/미디어",
  REP: "오라클",
  ZEC: "프라이버시",
  DASH: "결제/송금",
  XMR: "프라이버시",
  DCR: "거버넌스/투표",
  IOTA: "IoT/데이터",
  XLM: "결제/송금",
  POWR: "에너지/거래",
  POLY: "보안/토큰화",
  CHZ: "스포츠/팬토큰",

  // 결제/인프라
  ACH: "결제/송금",
  XCN: "결제/송금",
  REQ: "결제/인보이스",
  XYO: "위치 오라클/결제",
  AMP: "결제 담보 토큰",
  MTL: "결제/라이선스",

  // 인터체인/브릿지
  KSM: "인터체인",
  ZRO: "인터체인",
  STG: "인터체인",
  W: "인터체인/브릿지",
  CELR: "인터체인/브릿지",

  // 기타 유틸리티
  GAS: "L1 유틸리티",
  ONG: "L1 유틸리티",
  VTHO: "L1 유틸리티",
  TFUEL: "인프라/미디어",

  // 추가 DeFi
  RDNT: "렌딩",
  FRXETH: "스테이킹/LST",
  STETH: "스테이킹/LST",
  RETH: "스테이킹/LST",

  // 추가 신규 코인들
  GRASS: "데이터 마켓/브라우저",
  PUMP: "DEX/런치패드",
  DRIFT: "파생/Perp",
  ZETA: "파생/Perp",
  SOLV: "RWA/디파이",
  LISTA: "LRT/리스티킹",
  BABY: "스테이킹/LST",
  AVAIL: "모듈러",
  TIA: "모듈러",
  MANTA: "L2/ZK",
  ASTR: "L1/인터체인",
  CARV: "게이밍 DID/데이터",
  SONIC: "SVM 인프라·앱",
  LAYER: "솔레이어",
  ORDER: "오덜리 네트워크",
  PEAQ: "DePIN/머신 경제",
  ALT: "롤업 인프라/애그리게이션",
  AKT: "분산 컴퓨팅/DePIN",
  RLC: "인프라/컴퓨팅",
  GLM: "분산 컴퓨팅/DePIN",
  POKT: "인프라/노드",
  ANKR: "인프라/스테이킹",
  FLUX: "인프라/분산컴퓨팅",

  // 소셜/콘텐츠
  MASK: "소셜/아이덴티티",
  ENS: "소셜/아이덴티티",
  LENS: "소셜/아이덴티티",
  AUDIO: "음악 스트리밍/콘텐츠",
  LIVEPEER: "인프라/미디어",
  COS: "콘텐츠 플랫폼/소셜",
  HIVE: "소셜/아이덴티티",
  STEEM: "소셜/아이덴티티",

  // 기타 분류되지 않은 코인들
  DAO: "DAO 툴링/거버넌스",
  SAFE: "금고/멀티시그",
  GNO: "DAO/멀티시그·DeFi",
  SWISE: "스테이킹/LST",
  COW: "DEX/MEV",
  RSS3: "인프라/인덱싱",
  SLF: "DID/지갑",
  KEY: "보안/인증",
  T: "프라이버시",
  OBSR: "프라이버시",
  JASMY: "IoT/데이터",
  WOO: "디파이/유동성",
  SFP: "월렛/보안 유틸리티",
  BICO: "인프라/지갑·레저",
  C98: "월렛/디파이 허브",
  HOOK: "교육·소셜·게이미피케이션",
  EDU: "에듀테크/콘텐츠",
  HIGH: "메타버스·커머스",
  IQ: "콘텐츠/지식플랫폼",
  OSMO: "Cosmos/DEX",
  JUNO: "Cosmos/스마트컨트랙트",
  EVMOS: "Cosmos/EVM",
  SCRT: "Cosmos/프라이버시",
  LUNA: "Cosmos/스테이블",
  UST: "Cosmos/스테이블",
  MIR: "Cosmos/신세틱",
  ANC: "Cosmos/렌딩",

  // 빗썸에서 실제로 제공하는 추가 심볼들
  A: "기타/테스트",
  ELF: "L1/특화",
  SNT: "소셜/아이덴티티",
  CTXC: "IoT/데이터",
  CVC: "소셜/아이덴티티",
  IOST: "L1",
  AMO: "소셜/아이덴티티",
  ORBS: "L1",
  MIX: "기타",
  CRO: "L1",
  CHR: "L1/특화",
  FCT2: "기타",
  MEV: "DEX/MEV",
  SXP: "결제/송금",
  EL: "기타",
  XPR: "기타",
  EGG: "기타",
  ARPA: "프라이버시",
  CTC: "기타",
  APM: "기타",
  AERGO: "L1",
  EVZ: "기타",
  AWE: "기타",
  BEL: "기타",
  POLA: "기타",
  ADP: "기타",
  DVI: "기타",
  GHX: "기타",
  CBK: "기타",
  MVC: "기타",
  BLY: "기타",
  BIOT: "기타",
  SOFI: "기타",
  GRACY: "기타",
  OXT: "프라이버시",
  MAPO: "인터체인",
  AQT: "기타",
  WIKEN: "기타",
  PUNDIX: "결제/송금",
  SWAP: "기타",

  // 추가 코인들 - 문서 기반 매핑
  MNT: "L2",
  OMNI: "인터체인",
  PLUME: "RWA/디파이",
  FLOCK: "AI/데이터",
  PROVE: "인프라/ZK",
  AVL: "DeFi/비트코인",
  IP: "IP/콘텐츠",
  SD: "스테이킹/LST",
  SIGN: "GameFi/플랫폼",
  SOON: "인프라/롤업",
  HOME: "RWA/스테이블",
  HFT: "DEX/애그리게이션",
  POLYX: "RWA/증권토큰",
  BMT: "데이터/분석",
  MERL: "L2/비트코인",
  TOWNS: "소셜/커뮤니티",
  REI: "L1/특화",
  BLUE: "파생/Perp",
  MOCA: "GameFi/NFT",
  ERA: "롤업 인프라/RaaS",
  OM: "RWA/디파이",
  NMR: "AI/데이터",
  ZTX: "GameFi/메타버스",
  ID: "소셜/아이덴티티",
  XPLA: "L1/게임특화",
  C: "인프라/데이터",
  CSPR: "L1",
  STX: "L2/비트코인",
  SPURS: "스포츠/팬토큰",
  ZRC: "L2/ZK",
  BOA: "L1/특화",
  GAME2: "GameFi/NFT",
  FITFI: "M2E/피트니스",
  WAXL: "인터체인/브릿지",
  REZ: "LRT/리스티킹",
  MBX: "GameFi/퍼블리싱",
  OAS: "L1/게임특화",
  PCI: "결제/상거래",
  A8: "게이밍 길드",
  ARDR: "L1/사이드체인",

  // 문서에서 추가로 발견된 코인들
  ATH: "DePIN/GPU",
  FORT: "보안/인프라",
  ACE: "GameFi/L1",
  WAL: "스토리지/인프라",
  HAEDAL: "DeFi/유동성스테이킹",
  H: "DID/신원증명",
  SYRUP: "DeFi/대출",
  PROMPT: "AI/콘텐츠생성",

  OGN: "콘텐츠/플랫폼",
  COTI: "결제/송금",
  BNT: "DEX/AMM",
  XVS: "렌딩",
  UOS: "한국/L1",
  RSR: "스테이블코인",
};
